<footer class="footer">
    <div class="container">
        {!! setting('sys_footer') !!}
{{--        <p style="text-align:center"><a class="footer-link-txt" href="https://napgamegiare.net/tin-tuc/napgamegiarenet-dia-chi-nap-game-gia-re-uy-tin-an-toan-va-chiet-khau-cao">Uy t&iacute;n của ch&uacute;ng t&ocirc;i</a>&nbsp;| <a class="footer-link-txt" href="https://napgamegiare.net/tin-tuc/dieu-khoan-su-dung-website-napgamegiarenet">Điều khoản sử dụng</a> | <a class="footer-link-txt" href="https://napgamegiare.net/tin-tuc/chinh-sach-website-napgamegiarenet">Ch&iacute;nh s&aacute;ch bảo mật</a></p>--}}

{{--        <p><a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-kim-cuong-free-fire">Nạp Kim Cương Free Fire</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-quan-huy-lien-quan">Nạp Qu&acirc;n Huy Li&ecirc;n Qu&acirc;n</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-rp-lol-lien-minh">Nạp RP LOL</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-uc-pubg-mobile">Nạp UC PUBG Mobile</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/mua-ngoc-nro">Mua Ngọc NRO</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/mua-xu-ninja-school">Mua Xu Ninja School</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/mua-robux">Mua Robux</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-fc-fo4-fifa-online-4">Nạp FC FO4</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/mua-vang-nro">Mua V&agrave;ng NRO</a> |&nbsp;<a class="footer-link-txt" href="https://napgamegiare.net/mua-the">Mua Thẻ Game Gi&aacute; Rẻ</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/ban-tien-bangiftcode">Nạp BanGiftcode</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-can-nguyen-toc-chien">Nạp Căn Nguy&ecirc;n Tốc Chiến</a> |&nbsp;<a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-fc-fifa-online-4-m-vn">Nạp FC FO4 M</a> | <a class="footer-link-txt" href="https://muathengay.com">Mua Thẻ Garena</a> | <a class="footer-link-txt" href="https://napgamegiare.net/dich-vu/nap-play-together">Nạp Đ&aacute; Qu&yacute; Play Together</a> | <a class="footer-link-txt" href="https://napgameauto.com/">Nạp Game Auto</a>&nbsp;| <a class="footer-link-txt" href="https://napgame24h.net">Nạp Game 24h</a>&nbsp;|&nbsp;<a class="footer-link-txt" href="https://napgame3s.net">Nạp Game 3s</a>&nbsp;| <a class="footer-link-txt" href="https://napgamesieure.net">Nạp Game Si&ecirc;u Rẻ</a>&nbsp;| <a class="footer-link-txt" href="https://napgamenhanh.net">Nạp Game Nhanh</a>&nbsp;&nbsp;| <a class="footer-link-txt" href="https://napgameviet.com">Nạp Game Việt</a>&nbsp;| <a class="footer-link-txt" href="https://napgameuytin.com">Nạp Game Uy T&iacute;n</a>&nbsp;| <a class="footer-link-txt" href="https://quanhuylienquan.com/dich-vu/nap-quan-huy-lien-quan">Nạp Li&ecirc;n Qu&acirc;n</a>&nbsp;&nbsp;| <a class="footer-link-txt" href="https://kimcuongfreefire.vn/dich-vu/nap-kim-cuong-free-fire">Nạp Free Fire</a></p>--}}

{{--        <div><strong><span style="color:#000000">&copy; 2022&nbsp;</span><a href="https://napgamegiare.net/"><span style="color:#000000">NAPGAMEGIARE.NET</span></a></strong></div>--}}

    </div>
</footer>
