<?php


return [
    'charge' => [
        'key'=>"charge",
        'title'=>"Nạp thẻ tự động",
        'status' => [
            '1' => 'Thẻ đúng',
            '0' => 'Thẻ sai',
            '2' => 'Chờ xử lý',
            '3' => 'Sai mệnh giá',
            '999' => 'Lỗi nạp thẻ',
            '-999' => 'Lỗi nạp thẻ',
            '-1' => 'Phát sinh lỗi nạp thẻ',
        ],
        'key_encrypt' => env('ENCRYPT_CHARGING'),
    ],
    'tranfer' => [
        'key'=>"charge",
        'title'=>"Nạp ATM tự động",
        'status' => [
            '1' => 'Thành công(Đúng số tiền)',
            '0' => 'Thất bại',
            '2' => 'Chờ xử lý',
            '3' => 'Thành công(Sai số tiền)',
        ],
    ],
    'acc' => [
        'key'=>"charge",
        'encrypt_key' => '2314ku',
        'status' => [
//            1 => 'Chưa bán',
            0 => 'Thành công',
            2 => 'Chờ xử lý',
            3 => 'Đang check thông tin',
            4 => 'Sai thông tin',
            5 => 'Đã xoá',
            6 => 'Check lỗi'],
        'price' => [
            '0-50000' => 'Dưới 50K',
            '50000-200000' => 'Từ 50K - 200K',
            '200000-500000' => 'Từ 200K - 500K',
            '500000-1000000' => 'Từ 500K - 1 Triệu',
            '1000000-5000000' => 'Trên 1 Triệu',
            '5000000-10000000' => 'Trên 5 Triệu',
            '10000000' => 'Trên 10 Triệu',
        ],
    ],
    'txns' => [
        'trade_type' => [
            '1' => 'Nạp thẻ tự động',
            '2' => 'Nạp thẻ chậm',
            '3' => 'Chuyển tiền',
            '4' => 'Nhận tiền',
            '5' => 'Rút tiền',
            '6' => 'Cộng tiền',
            '7' => 'Trừ tiền',
            '8' => 'Tiền thưởng',
            '9' => 'Thanh toán bán nick',
            '10' => 'Đặt cọc (Trả góp)',
            '11' => 'Hoàn tiền',
            '12' => 'Thanh toán dịch vụ',
            '13' => 'Hoàn tất dịch vụ',
            '14' => 'Thanh toán mua thẻ',
            '15' => 'Thanh toán mua phụ kiện',
            '101' => 'Tăng số dư',
            '102' => 'Giảm số dư',
            '103' => 'Chuyển nhận tiền',
            '104' => 'Cộng trừ tiền',
            '105' => 'Mua tài khoản game',
            '106' => 'Mua kim cương',
            '107' => 'Vòng quay may mắn',
            '108' => 'Vòng quay vật phẩm',
            '109' => 'Lật hình vật phẩm',
            '110' => 'Lật hình trúng nick',
            '111' => 'Quay hình trúng vp',
            '112' => 'Quay hình trúng nick',
            '113' => 'Quay hình trúng tiền',
            '114' => 'Vòng quay trúng tiền',
            '115' => 'Lật hình trúng tiền',
            '116' => 'Quay xèng trúng vp',
            '117' => 'Quay xèng trúng nick',
            '118' => 'Quay xèng trúng tiền',
            '119' => 'Vòng quay trúng nick',
        ],
        'status' => [
            '0' => 'Không thành công',
            '1' => 'Thành công',
            '2' => 'Chờ xử lý',
        ],
    ],
];
