<?php
return [
    'theme_5_route-name-header' => [            // presence alias
        'homeIndex',
        'getDepositAuto',
        'getListMobile',
        'profile',
        'login',
        'getCategory',
    ],
    'theme_5_route-name-menu-bottom' => [            // presence alias
        'getThongTin',
        'getLogsStore',
        'getShowLogsStore',
        'info',
        'getChargeDepositHistory',
        'getStoreCard',
        'getBuyAccountHistory',
        'getChargeDepositHistory',
        'getChargeDepositHistory',
        'getChargeDepositHistory',
    ],
    'theme_dup_route-name-header' => [            // presence alias
        'homeIndex',
        'getIndex',
        'accIndex',
        'accDetail',
        'accList',
        'login',
        'register',
        'getCategory',
        'serviceList',
        'serviceDetail',
        'articleList',
        'articleDetail',
    ],
];
